services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: parikshithpalegar
      POSTGRES_DB: kitty
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432' # Expose PostgreSQL to the host
    networks:
      - app-network

  app:
    build: .
    container_name: svelte_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://kitty:parikshithpalegar@localhost:5432/kitty'
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
