services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: parikshithpalegar
      POSTGRES_DB: kitty
    volumes:
      - ./custom_pgdata:/var/lib/postgresql/data # Use a different path for the volume
    ports:
      - '4321:5432' # Expose PostgreSQL to the host

volumes:
  pgdata:
    driver: local
